spring:
  datasource:
    url: jdbc:h2:mem:test1

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: none

    properties:
      hibernate:
        format_sql: true

    show-sql: false

logging:
  level:
    ROOT: FATAL
